In [1]:
import pandas as pd

In [2]:
# reading csv file
df_car_sales = pd.read_csv('Car_sales.csv')
df_car_sales.head()

,Manufacturer,Model,Sales_in_thousands,__year_resale_value,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Wheelbase,Width,Length,Curb_weight,Fuel_capacity,Fuel_efficiency,Latest_Launch,Power_perf_factor
0,Acura,Integra,16.919,16.360,Passenger,21.50,1.8,140.0,101.2,67.3,172.4,2.639,13.2,28.0,2/2/2012,58.280150
1,Acura,TL,39.384,19.875,Passenger,28.40,3.2,225.0,108.1,70.3,192.9,3.517,17.2,25.0,6/3/2011,91.370778
2,Acura,CL,14.114,18.225,Passenger,NaN,3.2,225.0,106.9,70.6,192.0,3.470,17.2,26.0,1/4/2012,NaN
3,Acura,RL,8.588,29.725,Passenger,42.00,3.5,210.0,114.6,71.4,196.6,3.850,18.0,22.0,3/10/2011,91.389779
4,Audi,A4,20.397,22.255,Passenger,23.99,1.8,150.0,102.6,68.2,178.0,2.998,16.4,27.0,10/8/2011,62.777639

In [3]:
# selecting columns
df_car_sales = df_car_sales[['Manufacturer','Sales_in_thousands','Vehicle_type',
                              'Price_in_thousands','Engine_size','Horsepower','Fuel_capacity']]

In [4]:
# showing dataframe
df_car_sales

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.50,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.40,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.00,3.5,210.0,18.0
4,Audi,20.397,Passenger,23.99,1.8,150.0,16.4
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.40,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.50,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.80,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.50,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.00,2.9,201.0,21.1

In [9]:
# calculating number of unique values
df_car_sales.nunique()

Manufacturer           30
Sales_in_thousands    157
Vehicle_type            2
Price_in_thousands    152
Engine_size            31
Horsepower             66
Fuel_capacity          55
dtype: int64

In [11]:
df_car_sales['Vehicle_type'].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [10]:
df_car_sales['Manufacturer'].unique()

array(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet',
       'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti',
       'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mitsubishi', 'Mercury',
       'Mercedes-B', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac',
       'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen',
       'Volvo'], dtype=object)

In [12]:
df_car_sales['Engine_size'].unique()

array([1.8, 3.2, 3.5, 2.8, 4.2, 2.5, 3.1, 3.8, 4.6, 3. , 5.7, 2.2, 3.4,
       1. , 2.7, 2. , nan, 8. , 5.2, 3.9, 2.4, 4. , 1.6, 2.3, 1.5, 4.7,
       5.4, 3.3, 4.3, 5. , 1.9, 2.9])

# 1. agg()

In [14]:
# calculating the sum of sales in thousands
df_car_sales['Sales_in_thousands'].agg('sum')

np.float64(8320.698)

In [20]:
# calculating the mean of numeric columns
df_car_sales.select_dtypes(include='number').agg('mean').round(2)

Sales_in_thousands     53.00
Price_in_thousands     27.39
Engine_size             3.06
Horsepower            185.95
Fuel_capacity          17.95
dtype: float64

In [22]:
# calculating the mean and count values
df_car_sales.select_dtypes(include='number').agg(['mean', 'count']).round(2)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
mean,53.0,27.39,3.06,185.95,17.95
count,157.0,155.00,156.00,156.00,156.00

In [27]:
# Applying different aggregation fuctions to a column:
# calculating the sum and mean of 'Sales_in_thousands'
# and sum and max of 'Price_in_thousands'

df_car_sales.agg({'Sales_in_thousands':['sum', 'mean'],
                  'Price_in_thousands':['sum', 'max']}).round(2)

      Sales_in_thousands  Price_in_thousands
sum               8320.7             4245.57
mean                53.0                 NaN
max                  NaN               85.50

In [30]:
# applying aggregate functions over the columns. observation:
# df_car_sales[['Sales_in_thousands', 'Price_in_thousands']].agg('sum', axis=1) (NaN is considered 0)
# is equivalent to calculate the sum df_car_sales['Sales_in_thousands'] + df_car_sales['Price_in_thousands']
# (if there is a NaN value, the result of the operation is NaN)

In [32]:
# aggregate different functions and rename the index of the resulting dataframe

df_car_sales.agg( x = ('Sales_in_thousands', 'sum'),
                   y = ('Price_in_thousands', 'sum')).round(2)

   Sales_in_thousands  Price_in_thousands
x              8320.7                 NaN
y                 NaN             4245.57

# 2. The Split-Apply-Combine Strategy

In [15]:
df_car_sales['Vehicle_type'].value_counts()

Vehicle_type
Passenger    116
Car           41
Name: count, dtype: int64

In [6]:
# splitting data into separate groups

passenger_filter = df_car_sales['Vehicle_type'] == 'Passenger'
car_filter = df_car_sales['Vehicle_type'] == 'Car'
# we got boolean values in this series

In [13]:
# applying an operation
passenger_average = df_car_sales[passenger_filter]['Sales_in_thousands'].mean().round(2)
car_average = df_car_sales[car_filter]['Sales_in_thousands'].mean().round(2)

In [ ]:
# applying df_car_sales[passenger_filter] we only got the observations whose 'Vehicle_type' is Passenger
# then with the operation we obtain the average 'Sales_in_thousands' but only for the passenger Vehicle_type

In [14]:
# combining results
pd.DataFrame({'Vehicle_type':['Car', 'Passenger'],
              'Sales_in_thousands':[car_average, passenger_average]})

  Vehicle_type  Sales_in_thousands
0          Car               80.62
1    Passenger               43.23

# 3. groupby()

The groupby() method allows us group data into categories. And then we can apply some aggregate functions\
to calculate different values such as the sum, the mean, and so on. And we can count the values inside each category.

In [25]:
# group by Vehicle_type and calculate the mean

# Selecting only numeric columns
numerical_cols = df_car_sales.select_dtypes(include='number').columns

# Grouping by 'Vehicle_type' and calculating the mean only of numeric columns
df_car_sales.groupby('Vehicle_type')[numerical_cols].mean().round(2)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,
Car,80.62,26.32,3.52,186.40,21.90
Passenger,43.23,27.76,2.90,185.79,16.59

In [27]:
# group by Manufacturer
groupby_obj = df_car_sales.groupby('Manufacturer')

In [28]:
# the groupby_obj
groupby_obj

In [29]:
# groups attribute and jeys
groupby_obj.groups

{'Acura': [0, 1, 2, 3], 'Audi': [4, 5, 6], 'BMW': [7, 8, 9], 'Buick': [10, 11, 12, 13], 'Cadillac': [14, 15, 16, 17, 18], 'Chevrolet': [19, 20, 21, 22, 23, 24, 25, 26, 27], 'Chrysler': [28, 29, 30, 31, 32, 33, 34], 'Dodge': [35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45], 'Ford': [46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56], 'Honda': [57, 58, 59, 60, 61], 'Hyundai': [62, 63, 64], 'Infiniti': [65], 'Jaguar': [66], 'Jeep': [67, 68, 69], 'Lexus': [70, 71, 72, 73, 74, 75], 'Lincoln': [76, 77, 78], 'Mercedes-B': [92, 93, 94, 95, 96, 97, 98, 99, 100], 'Mercury': [86, 87, 88, 89, 90, 91], 'Mitsubishi': [79, 80, 81, 82, 83, 84, 85], 'Nissan': [101, 102, 103, 104, 105, 106, 107], 'Oldsmobile': [108, 109, 110, 111, 112, 113], 'Plymouth': [114, 115, 116, 117], 'Pontiac': [118, 119, 120, 121, 122, 123], 'Porsche': [124, 125, 126], 'Saab': [127, 128], 'Saturn': [129, 130, 131, 132, 133], 'Subaru': [134, 135], 'Toyota': [136, 137, 138, 139, 140, 141, 142, 143, 144], 'Volkswagen': [145, 146, 147, 148, 149, 150], 'Volvo': [151, 152, 153, 154, 155, 156]}

In [31]:
groupby_obj.groups.keys()

dict_keys(['Acura', 'Audi', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ford', 'Honda', 'Hyundai', 'Infiniti', 'Jaguar', 'Jeep', 'Lexus', 'Lincoln', 'Mercedes-B', 'Mercury', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Saab', 'Saturn', 'Subaru', 'Toyota', 'Volkswagen', 'Volvo'])

In [30]:
# in the keys we have the names of the groups (categories in Manufacturers), and in the values we have the indexes.
# for example, the category Audi has the indexes [4, 5, 6], so this means that the 4th, 5th and 5th rows has this Audi category

In [32]:
# get a specific group within the Manufacturer column
groupby_obj.get_group('Ford')

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
46,Ford,70.227,Passenger,12.070,2.0,110.0,12.7
47,Ford,113.369,Passenger,21.560,3.8,190.0,15.7
48,Ford,35.068,Passenger,17.035,2.5,170.0,15.0
49,Ford,245.815,Passenger,17.885,3.0,155.0,16.0
50,Ford,175.670,Passenger,12.315,2.0,107.0,13.2
51,Ford,63.403,Passenger,22.195,4.6,200.0,19.0
52,Ford,276.747,Car,31.930,4.0,210.0,21.0
53,Ford,155.787,Car,21.410,3.0,150.0,26.0
54,Ford,125.338,Car,36.135,4.6,240.0,26.0
55,Ford,220.650,Car,12.050,2.5,119.0,20.0
56,Ford,540.561,Car,26.935,4.6,220.0,25.1

In [ ]:
# and here we got the selection of Ford in the manufacturer column

In [35]:
# group by Manufacturer and calculate the mean

numerical_cols = df_car_sales.select_dtypes(include='number').columns
df_car_sales.groupby('Manufacturer')[numerical_cols].mean().round(2)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,19.75,30.63,2.92,200.00,16.40
Audi,13.52,39.98,2.93,220.00,19.53
BMW,15.50,33.10,2.70,185.33,17.23
Buick,60.50,26.78,3.62,206.25,17.75
Cadillac,22.44,40.25,4.50,256.00,20.80
Chevrolet,61.60,20.02,3.06,171.11,15.48
Chrysler,28.82,23.43,2.78,194.83,16.48
Dodge,82.74,24.21,3.71,199.55,21.58
Ford,183.88,21.05,3.33,170.09,19.06
Honda,118.53,20.28,2.52,160.40,17.08
Hyundai,45.78,12.17,1.97,126.67,14.53
Infiniti,23.71,29.46,3.00,227.00,18.50
Jaguar,15.47,42.80,3.00,240.00,18.40
Jeep,97.72,20.99,3.50,168.33,19.83
Lexus,17.81,44.06,3.62,245.83,20.53
Lincoln,28.54,41.69,4.87,263.33,23.00
Mercedes-B,13.01,52.92,3.42,232.22,18.92
Mercury,39.67,20.75,3.15,163.83,17.83
Mitsubishi,25.84,22.17,2.80,165.14,18.29
Nissan,57.09,22.36,2.91,169.00,18.20
Oldsmobile,29.83,25.62,3.45,190.00,18.20
Plymouth,16.00,22.64,2.48,166.75,15.12
Pontiac,61.76,22.95,3.43,185.00,17.92
Porsche,4.04,62.47,3.17,272.33,17.00
Saab,10.65,29.61,2.15,177.50,17.70
Saturn,33.77,14.27,2.02,119.60,12.50
Subaru,40.07,21.40,2.50,165.00,16.40
Toyota,82.24,21.98,2.62,160.67,17.77
Volkswagen,34.87,17.70,1.97,120.83,14.70
Volvo,12.62,30.93,2.30,182.17,17.83

In [37]:
# group by Manufacturer and calculate the sum
df_car_sales.groupby('Manufacturer')[numerical_cols].sum().round(2)

,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Manufacturer,,,,,
Acura,79.00,91.90,11.7,800.0,65.6
Audi,40.56,119.94,8.8,660.0,58.6
BMW,46.50,99.29,8.1,556.0,51.7
Buick,242.02,107.12,14.5,825.0,71.0
Cadillac,112.18,201.27,22.5,1280.0,104.0
Chevrolet,554.36,180.20,27.5,1540.0,139.3
Chrysler,201.72,140.58,16.7,1169.0,98.9
Dodge,910.15,266.35,40.8,2195.0,237.4
Ford,2022.64,231.52,36.6,1871.0,209.7
Honda,592.67,101.38,12.6,802.0,85.4
Hyundai,137.33,36.50,5.9,380.0,43.6
Infiniti,23.71,29.46,3.0,227.0,18.5
Jaguar,15.47,42.80,3.0,240.0,18.4
Jeep,293.15,62.98,10.5,505.0,59.5
Lexus,106.84,264.33,21.7,1475.0,123.2
Lincoln,85.63,125.07,14.6,790.0,69.0
Mercedes-B,117.12,476.25,30.8,2090.0,170.3
Mercury,238.00,124.49,18.9,983.0,107.0
Mitsubishi,180.90,155.17,19.6,1156.0,128.0
Nissan,399.64,156.52,20.4,1183.0,127.4
Oldsmobile,178.99,153.74,20.7,1140.0,109.2
Plymouth,64.00,90.57,9.9,667.0,60.5
Pontiac,370.53,137.70,20.6,1110.0,107.5
Porsche,12.13,187.42,9.5,817.0,51.0
Saab,21.31,59.22,4.3,355.0,35.4
Saturn,168.85,71.36,10.1,598.0,62.5
Subaru,80.13,42.79,5.0,330.0,32.8
Toyota,740.20,197.85,23.6,1446.0,159.9
Volkswagen,209.21,106.19,11.8,725.0,88.2
Volvo,75.74,185.60,13.8,1093.0,107.0

In [38]:
# group by Vehicle_type and count values
df_car_sales.groupby('Vehicle_type').count()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,41,41,40,40,40,40
Passenger,116,116,115,116,116,116

In [ ]:
# so for example, there are 41 values that corresponds to the Manufacturer inside the Car type

In [40]:
# find null values in columns
df_car_sales.isnull().sum()

Manufacturer          0
Sales_in_thousands    0
Vehicle_type          0
Price_in_thousands    2
Engine_size           1
Horsepower            1
Fuel_capacity         1
dtype: int64

In [ ]:
# so here we see only the Price_in_thousands, the Engine_size, the Horsepower and the Fuel_capacity
# have null values.

In [41]:
# group by Engine_size and count values without dropping NaN values
df_car_sales.groupby('Engine_size', dropna=False).count()

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Horsepower,Fuel_capacity
Engine_size,,,,,,
1.0,1,1,1,1,1,1
1.5,1,1,1,1,1,1
1.6,1,1,1,1,1,1
1.8,8,8,8,8,8,8
1.9,5,5,5,5,5,5
2.0,17,17,17,17,17,17
2.2,4,4,4,4,4,4
2.3,6,6,6,6,6,6
2.4,11,11,11,11,11,11
2.5,11,11,11,11,11,11
2.7,4,4,4,4,4,4
2.8,3,3,3,3,3,3
2.9,1,1,1,1,1,1
3.0,14,14,14,14,14,14
3.1,4,4,4,4,4,4
3.2,6,6,6,5,6,6
3.3,5,5,5,5,5,5
3.4,7,7,7,7,7,7
3.5,8,8,8,8,8,8
3.8,8,8,8,8,8,8
3.9,2,2,2,2,2,2
4.0,7,7,7,7,7,7
4.2,1,1,1,1,1,1
4.3,2,2,2,2,2,2
4.6,9,9,9,9,9,9
4.7,2,2,2,2,2,2
5.0,2,2,2,2,2,2
5.2,2,2,2,2,2,2
5.4,1,1,1,1,1,1
5.7,2,2,2,2,2,2
8.0,1,1,1,1,1,1
NaN,1,1,1,0,0,0

In [ ]:
# in the last row we have the null value

In [42]:
# And that's how the groupby() method works in Pandas.

# 4. groupby() and agg()

In [43]:
# finding the minimum and maximum values on each column
df_car_sales.groupby('Vehicle_type').min()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,Cadillac,9.126,11.528,2.0,119.0,15.1
Passenger,Acura,0.110,9.235,1.0,55.0,10.3

In [44]:
df_car_sales.groupby('Vehicle_type').max()

,Manufacturer,Sales_in_thousands,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
Vehicle_type,,,,,,
Car,Toyota,540.561,60.105,5.7,300.0,32.0
Passenger,Volvo,247.994,85.500,8.0,450.0,23.7

In [46]:
df_car_sales.groupby('Vehicle_type').agg(['min','max'])

             Manufacturer         Sales_in_thousands           \
                      min     max                min      max
Vehicle_type
Car              Cadillac  Toyota              9.126  540.561
Passenger           Acura   Volvo              0.110  247.994

             Price_in_thousands         Engine_size      Horsepower         \
                            min     max         min  max        min    max
Vehicle_type
Car                      11.528  60.105         2.0  5.7      119.0  300.0
Passenger                 9.235  85.500         1.0  8.0       55.0  450.0

             Fuel_capacity
                       min   max
Vehicle_type
Car                   15.1  32.0
Passenger             10.3  23.7

In [47]:
# setting a name for aggregated columns
# finding the min Engine_size and max Horsepower
df_car_sales.groupby('Vehicle_type').agg( min_engine_size = ('Engine_size', 'min'),
                                          max_horsepower = ('Horsepower', 'max') )

              min_engine_size  max_horsepower
Vehicle_type
Car                       2.0           300.0
Passenger                 1.0           450.0

In [ ]:
# so here we got the Vehicle_type in the index, because we grouped by Vehicle_type..
# and then we have here two columns, so 1st is the min_engine_size and this column has the 
# minimum value (2.0 and 1.0) and the 2nd column is the max_horsepower that has the max values

In [48]:
# calculating the sum of Sales_in_thousands and mean of Price_in_thousands
df_car_sales.groupby('Manufacturer').agg( sum_sales = ('Sales_in_thousands', 'sum'),
                                          mean_price = ('Price_in_thousands', 'mean') )

              sum_sales  mean_price
Manufacturer
Acura            79.005   30.633333
Audi             40.557   39.980000
BMW              46.505   33.096667
Buick           242.019   26.781250
Cadillac        112.178   40.254000
Chevrolet       554.365   20.022778
Chrysler        201.721   23.430833
Dodge           910.149   24.213636
Ford           2022.635   21.047273
Honda           592.674   20.277000
Hyundai         137.326   12.165667
Infiniti         23.713   29.465000
Jaguar           15.467   42.800000
Jeep            293.153   20.991667
Lexus           106.843   44.055000
Lincoln          85.634   41.690000
Mercedes-B      117.125   52.916667
Mercury         237.999   20.748333
Mitsubishi      180.895   22.167429
Nissan          399.635   22.360714
Oldsmobile      178.989   25.622833
Plymouth         64.001   22.642500
Pontiac         370.534   22.949167
Porsche          12.128   62.473333
Saab             21.306   29.610000
Saturn          168.850   14.271000
Subaru           80.135   21.395000
Toyota          740.205   21.982889
Volkswagen      209.212   17.698333
Volvo            75.740   30.933333

In [ ]:
# and here we have a dataframe, and in this df we grouped the data by Manufacturer
# and then we sum the values in the sum_sales column and then we calculated the mean
# in the mean_price column.. So here we have all the values for all the manufacturers.

In [50]:
# these operations are equivalent to using the functions

# df_car_sales.groupby('Manufcaturer').sum()['Sales_in_thousands']
# df_car_sales.groupby('Manufcaturer').mean()['Price_in_thousands']

# but with the aggregate functions we can group by a categorical variables, excecute
# multiple operations with a single instruction and get a dataframe as a result ...

In [51]:
# And that's how the groupby() and agg() methods can be used together.

# 5. Lambda

We're going to learn how to apply our own function to our group by object using the lambda function.

In [53]:
# getting actual sales and price values
df_car_sales.groupby('Manufacturer').sum().apply(lambda x: x*1000)[['Sales_in_thousands','Price_in_thousands']]

              Sales_in_thousands  Price_in_thousands
Manufacturer
Acura                    79005.0             91900.0
Audi                     40557.0            119940.0
BMW                      46505.0             99290.0
Buick                   242019.0            107125.0
Cadillac                112178.0            201270.0
Chevrolet               554365.0            180205.0
Chrysler                201721.0            140585.0
Dodge                   910149.0            266350.0
Ford                   2022635.0            231520.0
Honda                   592674.0            101385.0
Hyundai                 137326.0             36497.0
Infiniti                 23713.0             29465.0
Jaguar                   15467.0             42800.0
Jeep                    293153.0             62975.0
Lexus                   106843.0            264330.0
Lincoln                  85634.0            125070.0
Mercedes-B              117125.0            476250.0
Mercury                 237999.0            124490.0
Mitsubishi              180895.0            155172.0
Nissan                  399635.0            156525.0
Oldsmobile              178989.0            153737.0
Plymouth                 64001.0             90570.0
Pontiac                 370534.0            137695.0
Porsche                  12128.0            187420.0
Saab                     21306.0             59220.0
Saturn                  168850.0             71355.0
Subaru                   80135.0             42790.0
Toyota                  740205.0            197846.0
Volkswagen              209212.0            106190.0
Volvo                    75740.0            185600.0

In [55]:
# subtract the values from the mean of each group
numerical_cols = df_car_sales.select_dtypes(include='number').columns

df_car_sales.groupby('Manufacturer')[numerical_cols].apply(lambda x: x-x.mean())

# we calculate the mean of each category, for example the mean Price_in_thousands of the group Audi, 
# and then we subtract the mean to each value in the Price_in_thousands, for example.

                  Sales_in_thousands  Price_in_thousands  Engine_size  \
Manufacturer
Acura        0             -2.832250           -9.133333    -1.125000
             1             19.632750           -2.233333     0.275000
             2             -5.637250                 NaN     0.275000
             3            -11.163250           11.366667     0.575000
Audi         4              6.878000          -15.990000    -1.133333
...                              ...                 ...          ...
Volvo        152           -9.078333           -6.533333    -0.400000
             153            2.621667           -3.433333     0.100000
             154            4.907667           -2.133333     0.100000
             155           -9.130333           14.566667     0.000000
             156            6.345667            5.066667     0.600000

                  Horsepower  Fuel_capacity
Manufacturer
Acura        0    -60.000000      -3.200000
             1     25.000000       0.800000
             2     25.000000       0.800000
             3     10.000000       1.600000
Audi         4    -70.000000      -3.133333
...                      ...            ...
Volvo        152  -22.166667      -2.033333
             153  -14.166667       0.066667
             154  -14.166667       0.066667
             155   53.833333       0.666667
             156   18.833333       3.266667

[157 rows x 5 columns]

In [56]:
# and as we can see, this lambda function that we created shows us the values that are under the mean
# and over the mean. So we can recofnize which are good values.

In [57]:
# When aggrgate functions are applied inside the lambda function (for example, the mean)
# we apply this function to the groups that we get after using the group by method. 

# In this case, we grouped by 'Manufacturer' with the groupby() method, we calculated the
# mean over the Manufacturer groups, and we subtract the mean from the values..

In [58]:
# And that's how the lambda function works and how complex functions can be created using the apply method and the lambda function.

# 6. The filter() method

The filter() method helps us filter values based on an aggregate function when we use it with the groupby() method.

In [60]:
# calculating the mean of Sales_in_thousands
df_car_sales[numerical_cols].mean()

Sales_in_thousands     52.998076
Price_in_thousands     27.390755
Engine_size             3.060897
Horsepower            185.948718
Fuel_capacity          17.951923
dtype: float64

In [61]:
# filtering certain values out based on sum() and returning a subset
def filter_func(x):
    '''it filters groups based on 
    the sum of the sales in thousands'''
    return x['Sales_in_thousands'].sum() > 52    # we're going to filter based on this condition
# x represents a dataframe
    
df_filter = df_car_sales.groupby(['Manufacturer']).filter(filter_func)
df_filter 
# So here in my filter method we specify that we want to apply that function

,Manufacturer,Sales_in_thousands,Vehicle_type,Price_in_thousands,Engine_size,Horsepower,Fuel_capacity
0,Acura,16.919,Passenger,21.500,1.8,140.0,13.2
1,Acura,39.384,Passenger,28.400,3.2,225.0,17.2
2,Acura,14.114,Passenger,NaN,3.2,225.0,17.2
3,Acura,8.588,Passenger,42.000,3.5,210.0,18.0
10,Buick,91.561,Passenger,21.975,3.1,175.0,17.5
...,...,...,...,...,...,...,...
152,Volvo,3.545,Passenger,24.400,1.9,160.0,15.8
153,Volvo,15.245,Passenger,27.500,2.4,168.0,17.9
154,Volvo,17.531,Passenger,28.800,2.4,168.0,17.9
155,Volvo,3.493,Passenger,45.500,2.3,236.0,18.5
156,Volvo,18.969,Passenger,36.000,2.9,201.0,21.1

In [62]:
# all the values that are in this df passed the filter. So this means that the sum of the Sales
# (in each group) is greater than 52. For example, the sum of the sales in the Audi group is > 52, and so on.

In [70]:
# if we group by manufacturer, we filter the numerical cols and sum the sales in thousands
df_car_sales.groupby(['Manufacturer'])[numerical_cols].sum()['Sales_in_thousands'].sort_values().head(6)

Manufacturer
Porsche     12.128
Jaguar      15.467
Saab        21.306
Infiniti    23.713
Audi        40.557
BMW         46.505
Name: Sales_in_thousands, dtype: float64

In [71]:
# and sort them ascending, we obtain that the first 6 manufacturer's Sales are < 52.. so they shouldn't
# be in the previous df because they were filtered out. To verify this we can do the following:
df_car_sales[df_car_sales['Manufacturer'].isin(['Porsche','Jaguar','Saab','Infiniti','Audi','BMW'])].shape

(13, 7)

In [72]:
# the shape of this df is 13 rows * 7 columns. and now let's compare the shape of the original df
# and the shape of the df_filter, to see how many rows we lost in the filter.
df_car_sales.shape

(157, 7)

In [73]:
# and here we see that in the original df we had 157 rows
df_filter.shape

(144, 7)

In [74]:
# in the df_filter we had 144 row. So here we lost:
157-144

13

In [75]:
# here we lost 13 rows.. And those 13 rows belongs to these 6 manufacturers: 'Porsche','Jaguar','Saab','Infiniti','Audi','BMW'
# because these Manufacturers didn't pass the filter. So they have total Sales < 52

In [ ]:
# And that's how the filter method can be used with the group by object.