In [1]:
import pandas as pd

# concat()

In Pandas, we can use the concat() method to concatenate two dataframes. And there are two different\
ways to concatenate dataframes. We can concatenate dataframes vertically and horizontally.

axis = 0 means vertical concatenation (concatenating along the rows),\
axis = 1 means horizontal concatenation (concatenating along the columns)

pd.concat([df1, df2]), axis = 0 by default

# Concatenate vertically

In [3]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['E', 'F', 'G', 'H'],
                    'age': [40, 21, 19, 24]})

In [5]:
pd.concat([df1, df2], axis=0, ignore_index=True)

  id  age
0  A   30
1  B   23
2  C   25
3  D   22
4  E   40
5  F   21
6  G   19
7  H   24

In [ ]:
# and this is how the resulting df looks, df1 is above df2

In [6]:
# Given that we set ignore_index=True, we'll see we get 0, 1, 2, 3, ..., 7
# in the indexes. And we see we don't get the 0, 1, 2, 3 indexes repeated
# because we ignored the original indexes. So this df will have a new index
# ignoring the indexes from df1 and df2.

# Example

In [7]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)

In [8]:
# selecting the columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 
                       'genre', 'country']]

In [9]:
# extracting a 50% sample of the original dataframe (df_movies)
df_movies2 = df_movies.sample(frac=0.5, random_state=42)

In [10]:
# shape of the dataframes that we'll concatenate
df_movies.shape, df_movies2.shape

((85855, 5), (42928, 5))

In [13]:
# concatenating df_movies and df_sample (vertically along the rows)
df = pd.concat([df_movies, df_movies2], axis=0, ignore_index=True)
df

,imdb_title_id,title,year,genre,country
0,tt0000009,Miss Jerry,1894,Romance,USA
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
3,tt0002101,Cleopatra,1912,"Drama, History",USA
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy
...,...,...,...,...,...
128778,tt0426114,Moroz po kozhe,2007,"Thriller, Drama",Russia
128779,tt0095996,Rikky and Pete,1988,"Comedy, Drama",Australia
128780,tt0246514,Solo per il successo,2001,"Comedy, Romance",Germany
128781,tt0048087,I perversi,1955,"Drama, Thriller",UK
128782,tt0021933,Mani colpevoli,1931,"Drama, Crime",USA

In [14]:
# shape
df.shape

(128783, 5)

In [15]:
# And that's how vertical concatenation can be done in Pandas.