In [2]:
import pandas as pd

# Concatenate Horizontally

In [3]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'job': ['Doctor', 'Statistician', 
                            'Engineer', 'Developer']})

In [5]:
pd.concat([df1, df2], axis=1)

  id  age           job
0  A   30        Doctor
1  B   23  Statistician
2  C   25      Engineer
3  D   22     Developer

In [6]:
# And we get a single datafreme with the three columns.
# So we see the id, the age and the job in this single df

# Example

In [14]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [15]:
# selecting the columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 
                       'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

In [16]:
# shape of dataframes that we'll concatenate
print(df_movies.shape)
print(df_ratings.shape)

(85855, 5)
(85855, 3)

In [17]:
# concatenating df_movies and df_ratings on 'imdb_title_id' (horizontally)
df_movies.set_index('imdb_title_id', inplace=True)
df_movies.head()

,title,year,genre,country
imdb_title_id,,,,
tt0000009,Miss Jerry,1894,Romance,USA
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark"
tt0002101,Cleopatra,1912,"Drama, History",USA
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy

In [18]:
df_ratings.set_index('imdb_title_id', inplace=True)
df_ratings.head()

               total_votes  mean_vote
imdb_title_id
tt0000009              154        5.9
tt0000574              589        6.3
tt0001892              188        6.0
tt0002101              446        5.3
tt0002130             2237        6.9

In [20]:
df = pd.concat([df_movies, df_ratings], axis=1)
df

,title,year,genre,country,total_votes,mean_vote
imdb_title_id,,,,,,
tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...
tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [21]:
# and now we have this concatenation. So this df has the four columns of the df_movies
# and the two columns of the df_ratings, and here the index is the id column

In [22]:
# shape
df.shape

(85855, 6)

In [24]:
# And that's how two dataframes can be concatenated horizontally.