# 1. Merge()

In [1]:
import pandas as pd

In [6]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician', 
                            'Engineer', 'Developer']})

In [7]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [8]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E      Engineer
3  F     Developer

## 1.1 Inner Join

The Inner Join returns matching values between two tables. In this case, it will be the matching\
data between two dataframes. So if we have dataframe 1 on the left and dataframe 2 on the right, the\
data that they have in common is the data that will be in the middle (the intersection of the two sets).

And to write the code that produces this inner join, we have to use the merge() method:

df1.merge(df2, on='id', how='inner')

id is the column that both dataframes have in common, and there will be elements in common in this id column.

In [10]:
df_inner_join = df1.merge(df2, on='id', how='inner')
df_inner_join

  id  age           job
0  C   25        Doctor
1  D   22  Statistician

In [ ]:
# Solo aparecen esas filas porque df1 y df2 tienen en comun la columna id
# y porque en esa columna id tienen en comun los elementos C y D, esos son los
# elementos que están en la intersección de los dos conjuntos. Entonces junta
# las filas de ambas tablas y las pone una al lado de la otra, solo las filas 
# que tienen elementos en comun, en este caso C y D.

In [ ]:
# so we get a df that consists of these three columns and this data that corresponds to
# the C and D id.

In [12]:
# shape
print(df1.shape)
print(df2.shape)
print(df_inner_join.shape)

(4, 2)
(4, 2)
(2, 3)

In [ ]:
# The first two dfs have the same number of rows and columns. But the last df, so
# the df that represents the iner join has only two rows and three columns.. So
# this happens because these two dataframes have two rows in common, which are in the
# C and D rows. And here the three columns are the id, the job and the age column.

In [13]:
# And that's how the inner join can be made using the merge() method.

# Example

In [14]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [15]:
# selecting the columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 
                       'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]

In [19]:
# merging df_movies and df_ratings (inner join)
df_movies.merge(df_ratings, on='imdb_title_id', how='inner')    
# default value of the parameter how is inner
# pd.merge(df_movies, df_ratings, on='imdb_title_id') tambien funcionoa

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [17]:
# and now we can see that this df have the columns of df_movies: 'imdb_title_id',# 'title', 'year', 'genre', 'country'
# and 'total_votes', 'mean_vote' belong to df_ratings

# only the common 'imdb_title_id' are in this df

In [18]:
# And that's how an inner join between df_movies and df_ratings can be done.