In [2]:
import pandas as pd

## 1.2 Full Joins

Full joins allows us to join all the elements between two tables. So if we have a dataframe 1 on the left\
and a dataframe 2 on the right, the data that belong to both dfs will belong to the full join (the union of the two sets).

All the elements of the tables are taken by the full join because this full join takes all the elements\
in this two dataframes.

We have to find a column in common, a column that both dataframes have. And to make this full join we have\
to use the merge() method:

df1.merge(df2, on='id', how='outer')

on the "on" parameter we set it equal to the column that these two dfs have in common.\
in the "how" parameter we set it equal to outer, because this is a full join also known as an outer join.

In [3]:
df1 = pd.DataFrame({'id': ['A', 'B', 'C', 'D'],
                    'age': [30, 23, 25, 22]})
df2 = pd.DataFrame({'id': ['C', 'D', 'E', 'F'],
                    'job': ['Doctor', 'Statistician', 
                            'Engineer', 'Developer']})

In [5]:
df1

  id  age
0  A   30
1  B   23
2  C   25
3  D   22

In [6]:
df2

  id           job
0  C        Doctor
1  D  Statistician
2  E      Engineer
3  F     Developer

In [7]:
df1.merge(df2, on='id', how='outer')

  id   age           job
0  A  30.0           NaN
1  B  23.0           NaN
2  C  25.0        Doctor
3  D  22.0  Statistician
4  E   NaN      Engineer
5  F   NaN     Developer

In [9]:
# and now this produces the dataframe we want it. And here we see that the
# A and B id have null values (because df1 doesn't have the 'job' column) and
# the E and F id have null values (because df2 doesn't have the 'age' column)
# While the C and D id don't have null values because these are the elements in
# common between df1 and df2.

In [12]:
# shape
print(df1.shape)
print(df2.shape)
print(df1.merge(df2, on='id', how='outer').shape)

(4, 2)
(4, 2)
(6, 3)

## Example

In [13]:
# merging df_movies and df_ratings (outer join)

In [17]:
df_movies = pd.read_csv('IMDb movies.csv', low_memory=False)
df_ratings = pd.read_csv('IMDb ratings.csv', low_memory=False)

In [18]:
# selecting the columns
df_movies = df_movies[['imdb_title_id', 'title', 'year', 
                       'genre', 'country']]
df_ratings = df_ratings[['imdb_title_id', 'total_votes', 'mean_vote']]
# both dfs have in common the column imdb_title_id

In [19]:
df_movies.merge(df_ratings, on='imdb_title_id', how='outer')

,imdb_title_id,title,year,genre,country,total_votes,mean_vote
0,tt0000009,Miss Jerry,1894,Romance,USA,154,5.9
1,tt0000574,The Story of the Kelly Gang,1906,"Biography, Crime, Drama",Australia,589,6.3
2,tt0001892,Den sorte drøm,1911,Drama,"Germany, Denmark",188,6.0
3,tt0002101,Cleopatra,1912,"Drama, History",USA,446,5.3
4,tt0002130,L'Inferno,1911,"Adventure, Drama, Fantasy",Italy,2237,6.9
...,...,...,...,...,...,...,...
85850,tt9908390,Le lion,2020,Comedy,"France, Belgium",398,5.5
85851,tt9911196,De Beentjes van Sint-Hildegard,2020,"Comedy, Drama",Netherlands,724,7.9
85852,tt9911774,Padmavyuhathile Abhimanyu,2019,Drama,India,265,7.8
85853,tt9914286,Sokagin Çocuklari,2019,"Drama, Family",Turkey,194,9.4
85854,tt9914942,La vida sense la Sara Amat,2019,Drama,Spain,102,6.8

In [22]:
# and we get this dataframe that is the full join of the df_movies and the df_ratings..
# As we can see, these columns: 'title,'year','genre','country' belong to df_movies
# and these: 'total_votes','mean_vote', belong to df_ratings.

In [24]:
# And that's how full join between df_movies and df_ratings can be done.