In [1]:
import pandas as pd

## pivot()

This method reshapes data based on column values (it does not support data aggregation).

In [6]:
# reading and showing the dataset
df_gdp = pd.read_csv('gdp.csv')
df_gdp

      unid wbid      country  year        SES         gdppc  yrseduc  popshare
0        4  AFG  Afghanistan  1970   3.474212  7.090000e+02      NaN  0.003097
1        4  AFG  Afghanistan  1920  26.968016  7.317568e+02      NaN  0.003245
2        4  AFG  Afghanistan  1990   1.269530  6.040000e+02      NaN  0.002347
3        4  AFG  Afghanistan  1960  15.763076  7.390000e+02      NaN  0.003039
4        4  AFG  Afghanistan  2000   2.061114  5.650000e+02      NaN  0.003309
...    ...  ...          ...   ...        ...           ...      ...       ...
2081   716  ZWE     Zimbabwe  1940  52.746567  8.130000e+02      NaN  0.001113
2082   716  ZWE     Zimbabwe  2010  27.091389  1.388973e+06      NaN  0.002074
2083   716  ZWE     Zimbabwe  1990  59.110970  2.526072e+03      NaN  0.002039
2084   716  ZWE     Zimbabwe  1900  54.722645  6.010000e+02      NaN  0.000996
2085   716  ZWE     Zimbabwe  1960  53.811077  9.380000e+02      NaN  0.001268

[2086 rows x 8 columns]

In [5]:
# This df shows how the GDP evolves over the years for each country

In this example we're going to obtain a different view of the original data set to see\
the evolution of the GDP per capita over the years for each country.

In [8]:
# reshaping the dataframe with .pivot()
df_gdp.pivot(index='year', columns='country', values='gdppc')

# Returns reshaped DataFrame organized by given index / column values.

# Reshapes data (produce a "pivot" table) based on column values. Uses
# unique values from specified `index` / `columns` to form axes of the
# resulting DataFrame. This function does not support data
# aggregation, multiple values will result in a MultiIndex in the
# columns.

# quisiera que el dataframe tenga otra forma, por ejemplo que en las filas
# tenga cierta variable como indice (p. ej, el año), y en las columnas aparezcan otras variables
# (p. ej los paises, que cada pais se una columna independiente (y que no se repitan))
# y que en las celdas no aparezcan esos datos sino otros, (p. ej valores de pbi per capita)..
# entonces deberiamos cambiar la forma del df, seleccionar estas variables y, a su vez, seleccionar
# con que valores voy a rellenar las celdas de datos.

country,Afghanistan,Albania,Algeria,Angola,Argentina,Armenia,Australia,Austria,Bahrain,Bangladesh,...,Ukraine,United Arab Emirates,United Kingdom,United States,Uruguay,Venezuela,Vietnam,Yemen,Zambia,Zimbabwe
year,,,,,,,,,,,,,,,,,,,,,
1880,585.46509,522.00000,8.191860e+02,533.66669,1731.50,1041.0000,4285.0,2079.0,8.117675e+02,5.666667e+02,...,1041.0000,8.117675e+02,3477.0,3184.0,2.082000e+03,653.0,556.62793,811.76746,533.66669,5.336667e+02
1890,635.93024,598.00000,9.233721e+02,567.33331,2152.00,1139.0000,4458.0,2443.0,8.815349e+02,5.873333e+02,...,1139.0000,8.815349e+02,4009.0,3392.0,2.147000e+03,737.0,608.25580,881.53491,567.33331,5.673333e+02
1900,686.39532,685.00000,1.027558e+03,601.00000,2756.00,1237.0000,4013.0,2882.0,9.513023e+02,6.080000e+02,...,1237.0000,9.513023e+02,4492.0,4091.0,2.219000e+03,821.0,659.88373,951.30231,601.00000,6.010000e+02
1910,736.86047,780.00000,1.131744e+03,628.69232,3822.00,1430.0769,5210.0,3290.0,1.021070e+03,6.618461e+02,...,1430.0769,1.021070e+03,4611.0,4964.0,3.136000e+03,886.0,711.51166,1021.06980,628.69232,6.286923e+02
1920,731.75677,861.31250,1.201216e+03,682.62964,3473.00,1432.9333,4766.0,2412.0,1.242919e+03,6.518919e+02,...,1432.9333,3.833676e+03,4548.0,5552.0,2.674000e+03,1173.0,713.94592,1017.21620,682.62964,6.826296e+02
1930,702.83783,929.57141,1.255811e+03,747.81482,4080.00,1448.0000,4708.0,3586.0,1.529946e+03,6.145946e+02,...,1448.0000,7.821784e+03,5441.0,6213.0,4.301000e+03,3444.0,695.29730,981.81079,747.81482,7.478148e+02
1940,673.91895,965.28571,1.310405e+03,813.00000,4161.00,2144.0000,6166.0,3959.0,1.816973e+06,5.772973e+02,...,2144.0000,1.180989e+07,6856.0,7010.0,3.661000e+03,4045.0,676.64862,946.40540,813.00000,8.130000e+02
1950,645.00000,1001.00000,1.365000e+03,1052.00000,4987.00,2841.0000,7412.0,3706.0,2.104000e+03,5.400000e+02,...,2841.0000,1.579800e+04,6939.0,9561.0,4.659000e+03,7462.0,658.00000,911.00000,661.00000,7.010000e+02
1960,739.00000,1451.00000,2.088000e+03,1253.00000,5559.00,3945.0000,8791.0,6519.0,2.843000e+03,5.450000e+02,...,3945.0000,2.243300e+04,8645.0,11328.0,4.960000e+03,9646.0,799.00000,964.00000,960.00000,9.380000e+02
1970,709.00000,2004.00000,2.249000e+03,1768.00000,7302.00,5575.0000,12024.0,9747.0,3.788000e+03,6.300000e+02,...,5575.0000,2.455200e+04,10767.0,15030.0,5.184000e+03,10672.0,735.00000,1230.00000,1073.00000,1.282000e+03
1980,690.00000,2347.00000,3.152000e+03,961.00000,8206.00,6116.5884,14412.0,13759.0,4.388000e+03,5.490000e+02,...,5378.1763,2.770900e+04,12931.0,18577.0,6.555000e+03,10139.0,757.00000,2290.00000,911.00000,1.295000e+03
1990,604.00000,4557.40820,1.023888e+07,4806.43020,10833503.00,3735.5432,28572076.0,31265287.0,3.511256e+07,1.290431e+06,...,10463.9600,1.145188e+05,26769357.0,37062129.0,9.840727e+03,14450682.0,1501.13890,3353.78930,2308.60380,2.526072e+03
2000,565.00000,5470.01760,1.021110e+07,3831.00000,14924374.00,2918.5576,35244504.0,38812051.0,4.479152e+04,1.645717e+03,...,4797.3804,1.072065e+05,32961527.0,45986051.0,1.287478e+07,14417104.0,2649.71950,3911.21970,2092.25510,2.521347e+03
2010,1662.80350,9927.17580,1.289830e+07,6492.17680,18794.27,6507.9146,41363215.0,43174977.0,3.991270e+07,2.451305e+03,...,7824.4985,5.740674e+07,36195867.0,49372832.0,1.708241e+04,16563396.0,4486.26120,4481.55470,3263.39480,1.388973e+06

In [9]:
# So here, as we can see, we have the new view of this dataframe. And it looks much better, it's more readable..
# because we can see the GDP evolution over the years for each country..

## .pivot_table()

It creates a spreadsheet-style pivot table (and it supports data aggregation).

In [22]:
# reading and showing the dataset
df_sales = pd.read_excel('supermarket_sales.xlsx')    
df_sales

# antes de ejecutar estas lineas, abrir una nueva ventana de Anaconda Prompt,
# activar el entorno virtual en el que estamos trabajando y ejecutar pip install openpyxl

,Invoice ID,Branch,City,Customer type,Gender,Product line,Unit price,Quantity,Tax 5%,Total,Date,Time,Payment,cogs,gross margin percentage,gross income,Rating
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05,13:08:00,Ewallet,522.83,4.761905,26.1415,9.1
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08,10:29:00,Cash,76.40,4.761905,3.8200,9.6
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03,13:23:00,Credit card,324.31,4.761905,16.2155,7.4
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27,20:33:00,Ewallet,465.76,4.761905,23.2880,8.4
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08,10:37:00,Ewallet,604.17,4.761905,30.2085,5.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29,13:46:00,Ewallet,40.35,4.761905,2.0175,6.2
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02,17:16:00,Ewallet,973.80,4.761905,48.6900,4.4
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09,13:22:00,Cash,31.84,4.761905,1.5920,7.7
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22,15:33:00,Cash,65.82,4.761905,3.2910,4.1
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18,13:28:00,Cash,618.38,4.761905,30.9190,6.6

In [ ]:
# and here we can see we have different columns about what a specific person bought in a supermarket
# and here we have the 'Branch', the 'City', the 'Gender' and different data.

In [26]:
# making a pivot table and adding an aggregate function

# Filtrar solo columnas numéricas
numeric_cols = df_sales.select_dtypes(include='number').columns

# Crear la pivot table solo con esas columnas
df_sales.pivot_table(index="Gender", values=numeric_cols, aggfunc="sum")

,Quantity,Rating,Tax 5%,Total,Unit price,cogs,gross income,gross margin percentage
Gender,,,,,,,,
Female,2869,3489.2,7994.425,167882.925,27687.24,159888.50,7994.425,2385.714286
Male,2641,3483.5,7384.944,155083.824,27984.89,147698.88,7384.944,2376.190476

In [27]:
# making a pivot table, adding an aggregate function and selecting some columns
df_sales.pivot_table(index="Gender", 
                     values=["Quantity", "Total"], 
                     aggfunc="sum")

        Quantity       Total
Gender
Female      2869  167882.925
Male        2641  155083.824

In [ ]:
# so far we know that female spend 167882.925 and male spend 155083.824 in this supermarket 

# but with pivot tables, we can even know in which product lines this money is spent.

In [30]:
# making a pivot table that says how much male and female spend in each Product Line
df_sales.pivot_table(index="Gender",
                     columns="Product line",
                     values="Total", 
                     aggfunc="sum")

Product line,Electronic accessories,Fashion accessories,Food and beverages,Health and beauty,Home and lifestyle,Sports and travel
Gender,,,,,,
Female,27102.0225,30437.400,33170.9175,18560.9865,30036.8775,28574.7210
Male,27235.5090,23868.495,22973.9265,30632.7525,23825.0355,26548.1055

In [ ]:
# and now as we can see here, how much female and male spend in each product line..

# So we can quickly see, for example that male spend slightly more on Electronic accessories than female,
# female spend more money on Fashion accessories than male, and that kind of makes sense, and also in sports
# female spend more money than male..

# So we could easily see all of that by using the pivot_table() method in Pandas,